---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./config:/config
      - /mnt/RAID/public/Videos/:/videos #optional
      - /mnt/RAID/tyler/videos/MakeMKV:/makemkv #optional
    #ports:
      #- 7878:7878
    restart: unless-stopped

networks:
  default:
    name: radarr
    external: true
